service: wolf-trading
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  environment:
    ALERT_PARAMETER: wolf_alert_status
    ALERT_DURATION_PARAMETER: wolf_confluence_duration
    TABLE_NAME: wolf_confluence_table

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "ssm:*"
          Resource: "*"
        - Effect: "Allow"
          Action: "dynamodb:*"
          Resource: "*"

functions:
  - ${file(./resources/functions.yml)}

resources:
  - ${file(./resources/resources.yml)}
